[project]
name = "qosst-bob"
version = "0.10.4.dev0"
description = "Bob submodule of QOSST, containing modules for Bob client, the GUI, the DSP of Bob and parameters estimation."
authors = [
    { name = "Yoann Piétri", email="Yoann.Pietri@lip6.fr" },
    { name = "Valentina Marulanda Acosta", email="Valentina.Marulanda-Acosta@lip6.fr" },
    { name = "Ilektra Karakosta-Amarantidou", email="ilektra.karakostaamarantidou@studenti.unipd.it" },
    { name = "Matteo Schiavon", email="Matteo.Schiavon@lip6.fr" },
]

license = "GPL-3.0-only"
readme = "README.md"
classifiers = [
    "Development Status :: 4 - Beta",
    "Intended Audience :: Science/Research",
    "License :: OSI Approved :: GNU General Public License v3 (GPLv3)",
    "Natural Language :: English",
    "Operating System :: OS Independent",
    "Topic :: Scientific/Engineering :: Physics",
    "Topic :: Security :: Cryptography",
]
requires-python = ">=3.11, <3.15"

dependencies = [
    "qosst-hal @ git+https://github.com/qosst/qosst-hal@dev",
    "qosst-core @ git+https://github.com/qosst/qosst-core@dev",
    "qosst-skr @ git+https://github.com/qosst/qosst-skr@dev",
    "matplotlib>=3.7.1",
    "scipy>=1.15.0",
    "freesimplegui>=5.1.0"
]

[project.urls]
homepage = "https://github.com/qosst"
repository = "https://github.com/qosst/qosst-bob"
documentation = "https://qosst-bob.readthedocs.io/"

[dependency-groups]
dev = [
    "myst-parser>=4.0.0",
    "sphinx-prompt>=1.5.0",
    "sphinx-argparse-cli>=1.11.0",
    "setuptools>=67.6.1",
    "docstr-coverage>=2.2.0",
    "sphinx-rtd-theme>=3.0.0",
    "Sphinx>=8.1.0",
    "pylint>=3.3.0",
    "mypy>=1.3.0",
    "sphinxcontrib-programoutput>=0.17",
    "ipykernel>=6.26.0",
    "black>=23.9.1",
    "numba>=0.64.0"
]

[project.scripts]
qosst-bob-gui = "qosst_bob.gui.bobgui:main"
qosst-bob-excess-noise = "qosst_bob.excess_noise:main"
qosst-bob-optimize = "qosst_bob.optimization.commands:main"
qosst-bob-transmittance = "qosst_bob.transmittance:main"
qosst-bob-tools = "qosst_bob.tools.commands:main"
qosst-bob-offline-dsp = "qosst_bob.dsp.offline_dsp:main"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.hatch.build.targets.wheel]
packages = ["qosst_bob/"]

[tool.hatch.build.targets.wheel.force-include]
"qosst_bob/py.typed" = "qosst_bob/py.typed"
"qosst_bob/gui/logo.png" = "qosst_bob/gui/logo.png"

[tool.hatch.metadata]
allow-direct-references = true